### ISSUE TITLE
Chain halted when doing redelegation ( or unstaking)

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#263]
## Description and context

The odyssey devnet halted at block 5115. At that time, running redelegation operations and performance testing on the same time.

- Redelegation test: [Staking-49-02](https://www.notion.so/storyprotocol/124051299a5481a4a1cbc5b3037bde23?pvs=4) Redelegation unbonding period for fixed staking period,  stopped at [step 06.](https://github.com/storyprotocol/l1-tests/blob/43a7d4cb8e565dfcb271c395a744f2a144f1ed4d/tests/stake/redelegate.test.ts#L502)

       notice that step 03, 04, 06 all redelegate from validatior 4 to validator 1.

- Performance test: @[Performance-01](https://www.notion.so/storyprotocol/Performance-01-dc186fb7ca6240ef8daf4e52fc7ad403?pvs=24)-runOperation: Execute normal operation, stopped at [unstaking](https://github.com/storyprotocol/l1-tests/blob/refs/heads/debug-stake-tests-05/tests/performance.test.ts#L155).

ERROR:
```

2024-10-21 22:53:12.732 | 24-10-21 14:53:12.732 ERRO CONSENSUS FAILURE!!!                     module=consensus |  
-- | -- | --
  |   | 2024-10-21 22:53:12.732 | │ math/big.(*Int).Cmp(0x34da700?, 0xc00005ecd0?) |  
  |   | 2024-10-21 22:53:12.732 | │ goroutine 207 [running]: |  
  |   | 2024-10-21 22:53:12.732 | │ github.com/piplabs/story/client/x/evmstaking/keeper.Keeper.ExpectedRewardWithdrawals({{0x351e0c0, 0xc000617930}, {0x34da700, 0xc000d1f410}, {0x34e9818, 0xc001044350}, {0xc000ba8a20, 0x2c}, {0x7f1c4618b3c8, 0xc000f018b8}, ...}, ...) |  
  |   | 2024-10-21 22:53:12.732 | │ \t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x5e |  
  |   | 2024-10-21 22:53:12.732 | │ \t/home/runner/go/pkg/mod/github.com/piplabs/cosmos-sdk@v0.50.7-piplabs-v0.14/x/distribution/keeper/delegation.go:152 +0x452 |  
  |   | 2024-10-21 22:53:12.732 | │ github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.CalculateDelegationRewards({{0x34da700, 0xc00005ecd0}, {0x351e0c0, 0xc000617930}, {0x7f1c46189d18, 0xc000f018b8}, {0x7f1c46189d58, 0xc0019e3860}, {0x7f1c46189da0, 0xc000ef0300}, ...}, ...) |  
  |   | 2024-10-21 22:53:12.732 | │ runtime/debug.Stack() |  
  |   | 2024-10-21 22:53:12.732 | │ \t/home/runner/go/pkg/mod/cosmossdk.io/math@v1.3.0/dec.go:218 |  
  |   | 2024-10-21 22:53:12.729 | 24-10-21 14:53:12.729 ERRO Failed to process redelegate             err="failed to begin redelegation: period delegation already exists" stacktrace="[errors.go:39 redelegation.go:133 keeper.go:209 msg_server.go:112 tx.pb.go:290 msg_service_router.go:175 tx.pb.go:292 msg_service_router.go:198 baseapp.go:1015 baseapp.go:953 baseapp.go:762 abci.go:790 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:202 state.go:1772 state.go:1682 state.go:1617 state.go:1655 state.go:2335 state.go:2067 state.go:929 state.go:836 asm_amd64.s:1700]"


```

**Comment by limengformal** [comment]
[PR](https://github.com/piplabs/story/pull/273) approved and deployed.

[Staking-49-02](https://www.notion.so/storyprotocol/124051299a5481a4a1cbc5b3037bde23?pvs=4) passed.
